### PR TITLE
DynamoDB Update

### PR DESCRIPTION
**Pull request by wanicedude**

### CODE REVIEW

**Review by alvo254 — CHANGES_REQUESTED** [review]
You are missing outputs.tf, this allows us to use dynamoDB in other modules

**Comment by wanicedude** [comment]
I have updated the output file for the DynamoDB module. Thanks

**Review by alvo254 — CHANGES_REQUESTED** [review]
I cannot merge to main please test the code on your side and uncomment main.tf

**Comment by wanicedude** [comment]
> I cannot merge to main please test the code on your side and uncomment main.tf

Good day Chief. I have tested the code on my end and it works perfectly. The last update I pushed, the main.tf file comments were removed. Are you still seeing the update with comment on your end?

**Pull request closed without merging**
